# Generated by Django 4.0.4 on 2022-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='movies.actor', verbose_name='Актёры'),
        ),
    ]
